version: '3.3'

networks:
  web:
    external: true

services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306" # MariaDB Port
    container_name: mariadb
    labels:
      - "traefik.enable=false"

  redis-cache:
    image: redis:alpine
    volumes:
      - ./conf/redis-conf.d:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_cache.conf"]
    container_name: redis-cache
    labels:
      - "traefik.enable=false"

  redis-queue:
    image: redis:alpine
    volumes:
      - ./conf/redis-conf.d:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_queue.conf"]
    container_name: redis-queue
    labels:
      - "traefik.enable=false"

  redis-socketio:
    image: redis:alpine
    volumes:
      - ./conf/redis-conf.d:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_socketio.conf"]
    container_name: redis-socketio
    labels:
      - "traefik.enable=false"

  frappe:
    build: .
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
      - ./conf/redis-conf.d/redis_cache.conf:/home/frappe/frappe-bench/config/redis_cache.conf
      - ./conf/redis-conf.d/redis_queue.conf:/home/frappe/frappe-bench/config/redis_queue.conf
      - ./conf/redis-conf.d/redis_socketio.conf:/home/frappe/frappe-bench/config/redis_socketio.conf
    ports:
      - "8000" # Webserver Port
      - "9000:9000" # Socketio Port
      - "6787:6787" # File Watcher Port
    stdin_open: true
    tty: true
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    container_name: frappe
    labels:
      - traefik.backend=frappe
      - traefik.frontend.rule=Host:erp2.propelled.com.au
      - traefik.docker.network=web
      - traefik.port=8000
    networks:
      - default
      - web
